### ISSUE TITLE
[Sprint- 3, 상세 페이지] 게시글 상세 조회 / 게시글 수정,삭제  / 댓글 작성, 수정,삭제 

### ISSUE THREAD

**Issue by SeonminKim1** [SeonminKim1/SidePro-BE#16]
## 1. 기간
2022.07.23 (토) ~ 2022.07.25 (월) 

### (1) 게시글 상세 조회
- 메인 화면에서 게시글을 클릭하면 상세 페이지 게시글로 이동
- 상세 페이지에서 해당 게시글에 대한 정보 조회 (제목, 등록일, 날짜, 기술스택, 깃허브링크, 댓글, 북마크 여부 등)
- 해당 게시글 조회시 DB 조회수 +1

### (2) 게시글 수정/삭제
- 로그인 유저가 해당 게시글 작성자면 수정/삭제 버튼 활성화 
- 게시글 수정시 게시글 등록 Page 화면에 Default 값만 설정됨.

### (3) 댓글 작성/수정/삭제
- 로그인한 유저의 이름으로 댓글 작성 가능 (댓글달기)
- 댓글달기를 누르면 화면 하단 Comments에 댓글 추가  및 조회 가능
- 로그인 유저가 해당 댓글 작성자면 댓글 수정/댓글 삭제 버튼 활성화
- 수정 버튼을 누르면 input 창이 보인다.
- 삭제 버튼을 누르면 댓글이 삭제 된다.

### (4) 북마크 등록
- 북마크 버튼 선택/해제 하면 내 북마크에 추가/삭제 된다. (mypage에서 확인 가능)

## 3. 세부 구현 순서
- [X] (BE) 상세 게시글 조회 API 구현 #4 
- [X] (BE) 게시글 수정, 삭제 API 구현 #4 
- [X] (BE) 댓글 작성 , 수정, 삭제 API 구현 #4  
- [X] (BE) 북마크 등록 / 해제 API 구현 #4 
- [ ] (FE-BE) 게시글 조회시 조회수 DB 반영 확인
- [ ] (FE-BE) 게시글 수정, 삭제시 DB 저장 + 정상 작동여부 확인
- [ ] (FE-BE) 댓글 작성, 수정, 삭제시 DB 저장 + 정상 작동여부 확인
- [ ] (FE-BE) 북마크 등록 / 해제시 DB 반영 + 정상 작동 확인

## 4. 프론트 ISSUE 링크
- 

## 5. 와이어 프레임 화면
![image](https://user-images.githubusercontent.com/33525798/180594897-9814590d-c2a5-4892-ba5a-94e89e480092.png)
